os: windows
language: shell
before_install:
  - choco install python3 --params "/InstallDir:C:" --version 3.8.0
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip
script: python3 attendance-vbs.py
