os: windows
python: "3.8"
language: sh
before_install:
  - choco install python3
  - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
  - python -m pip install --upgrade pip wheel
script:
  - python -m attendance-vbs.py
