os: windows
language: shell
before_install:
  - choco install python3 --version 3.8.0
env: PATH=c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/bin:/c/Python38:/c/Python38/Scripts:$PATH
script:
  - source ~/.bashrc
  - python attendance-vbs.py
