os: windows
python: "3.8"
language: sh
before_install:
  - choco install python3 --params "/InstallDir:C:\"
  - export PATH="/c/Python310:/c/Python310/Scripts:$PATH"
  - choco install pip
  - python -m pip install --upgrade pip wheel
script:
  - python -m attendance-vbs.py
